on:
  issues:
    types: [opened, edited, deleted, closed, reopened, labeled, unlabeled]

jobs:
  testing:
    runs-on: ubuntu-latest
    name: WorkItem-Action testen
    steps:       
    - name: Create or Get WorkItem from Issue
      uses: Toolbastler/github-actions-issue-to-work-item@master
      id: workItem
      env:     
        ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'
        github_token: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'
        ado_organization: '${{ secrets.ADO_ORGANIZATION }}'
        ado_project: '${{ secrets.ADO_PROJECT }}'
        ado_area_path: '${{ secrets.ADO_AREA_PATH }}'
        ado_iteration_path: '${{ secrets.ADO_ITERATION_PATH }}'
        ado_wit: 'Issue' 
        ado_new_state: 'New'
        ado_close_state: 'Closed'
        ado_active_state: 'Active'  
        ado_bypassrules: false
        issue_id: 1
    - name: Return created WorkItem
      run: echo "WorkItem ${{ steps.workItem.outputs.WorkItemId }} created"
